#pragma once

#define EventChannel_AiDoorStateChange					0xD65C714E	// Sent by door components, ready by nav components.
#define EventChannel_BulletCollision					0xC2B811BC	// This is an event that gets generated when bullets hit things.
#define EventChannel_BulletImpactDamageSphere			0x10B6A637	// A damage sphere has been hit by a bullet.
#define EventChannel_CameraZooming						0x33DA0596	// The camera is performing a zoom in or out operation.
#define EventChannel_Collision							0xA7304155	// This is an event that gets generated when collisions happen.
#define EventChannel_ConstraintAudio					0xC92181B5	// This is an event that gets generated constraints contain moving bodies.
#define EventChannel_Destruction						0x98D831CD	// This is an event that gets generated when physics Destruction happens.
#define EventChannel_DisMountVehicle					0x9462BD58	// Character gets off vehicle.
#define EventChannel_DisMountVehicleCamera				0x64B91EE6	// Character gets off vehicle.
#define EventChannel_EntityDeath						0x0514B87F	// <No Info>
#define EventChannel_GameStat							0x6DEC0B5E	// Sent to track as a game stat event.
#define EventChannel_MountVehicle						0x7DADD094	// Character gets on vehicle.
#define EventChannel_MountVehicleCamera					0x1B2810C5	// Character gets on vehicle.
#define EventChannel_SceneLayerActivated				0x023A9418	// <No Info>
#define EventChannel_SceneLayerDeactivated				0xDA965C02	// <No Info>
#define EventChannel_ScreenMinimized					0x243A3B0	// This is an event that gets generated when the screen is minimized.
#define EventChannel_ScreenRestored						0x15AD5C0A	// This is an event that gets generated when the screen is restored.
#define EventChannel_StateMachine						0x5EC41105	// This is a generic event that gets generated by StateMachines.
#define EventChannel_Teleport							0xF76010DE	// "blahblah" - avg SD dev event description
#define EventChannel_UIControllerDisconnected			0x8031FEB6	// Handles controller disconnected.
#define EventChannel_UIControllerReconnected			0x0339F2B9	// Handles controller reconnected.
#define EventChannel_UIGarageScreenDeferredTask			0xF4659A1A	// <No Info>
#define EventChannel_UIScreenMouseInput					0xCBACA118	// This gets the mouse input events to the UI.
#define EventChannel_UIScreenTextInput					0xCCB4932C	// This gets the keyboard input events to the UI.
#define EventChannel_UIWardrobeScreenDeferredTask		0xDCB750C2	// <No Info>
#define EventChannel_VehicleDisabled					0xEBE646D4	// <No Info>
#define EventChannel_VehicleTakenDown					0xC2B77335	// <No Info>
#define EventChannel_ZoneLayout							0x15BD597F	// <No Info>