#pragma once

namespace UFG
{
	enum eActiveZoneClass
	{
		Always_Active = 0x0,
		PreferActive_ExtraLow_Ok = 0x1,
		PreferExtraLow_Proxy_Bad = 0x2,
		PreferExtraLow_Proxy_Ok = 0x3,
		PreferProxy_Inactive_Ok = 0x4,
		Always_Inactive = 0x5,
		Zone_Classes_Count = 0x6,
	};

	enum eAIObjectEnum
	{
		eAIOBJECTTYPE_UNKNOWN = 0x0,
		eAIOBJECTTYPE_DOOR = 0x1,
		eAIOBJECTTYPE_SLIDNG_GATE = 0x2,
		eAIOBJECTTYPE_SHUTTER_GATE = 0x3,
	};

	enum AiPathGoalMode
	{
		AiGoal_Replace = 0x0,
		AiGoal_Replace_Direct = 0x1,
		AiGoal_Append = 0x2,
	};

	namespace AiDriverComponent
	{
		enum eDriverMode
		{
			eDRIVER_MODE_STOP = 0,
			eDRIVER_MODE_WANDER,
			eDRIVER_MODE_GOTO,
			eDRIVER_MODE_CHASE,
			eDRIVER_MODE_FOLLOW,
			eDRIVER_MODE_STOP_AT,
			eDRIVER_MODE_RACE,
			eDRIVER_MODE_ESCORT,
		};

		enum eDriverRole
		{
			eDRIVER_ROLE_TRAFFIC = 0,
			eDRIVER_ROLE_RACER,
			eDRIVER_ROLE_ENEMY,
			eDRIVER_ROLE_ALLY,
			eDRIVER_ROLE_TAXI,
			eDRIVER_ROLE_COP,
			eDRIVER_ROLE_BUS,
			eDRIVER_ROLE_TRAM,
			eDRIVER_ROLE_FERRY,
			eDRIVER_ROLE_BOAT,
		};
	}

	namespace AimingPlayerComponent
	{
		enum eAimBlendMode
		{
			eAIM_BLEND_MODE_NONE = 0x0,
			eAIM_BLEND_MODE_FREEAIM = 0x1,
			eAIM_BLEND_MODE_FREEAIM_TARGET = 0x2,
			eAIM_BLEND_MODE_SUBTARGETING = 0x3,
		};

		enum eSoftLockTypeEnum
		{
			eSOFT_LOCK_NONE = 0x0,
			eSOFT_LOCK_ABSOLUTE = 0x1,
			eSOFT_LOCK_RELATIVE_LOCAL = 0x2,
			eSOFT_LOCK_RELATIVE_LOCAL_ORIENTED_TO_ORIGIN = 0x3,
			NUM_SOFT_LOCK_TYPES = 0x4,
		};
	}

	namespace CarCombat
	{
		enum Attack
		{
			Ram = 0x0,
			Sideswipe = 0x1,
			PitManeuvre = 0x2,
			Block = 0x3,
			Melee = 0x4,
			Projectile = 0x5,
			AnyAttack = 0x6,
			NumAttacks = 0x7,
		};

		enum FormationAttack
		{
			Box = 0x0,
			Box2 = 0x1,
			RollingRoadBlock = 0x2,
			AnyFormationAttack = 0x3,
			NumFormationAttacks = 0x4,
		};

		enum Position
		{
			Follow = 0x0,
			Behind = 0x1,
			RearCorner = 0x2,
			PitPosition = 0x3,
			Beside = 0x4,
			FrontCorner = 0x5,
			Front = 0x6,
			NumPositions = 0x7,
		};

		enum Side
		{
			Left = 0x0,
			Right = 0x1,
			Closest = 0x2,
			AnySide = 0x3,
			NumSides = 0x4,
		};
	}

	namespace CarAI
	{
		enum EEscortMode
		{
			AttackEnemy = 0x0,
			EscortObjective = 0x1,
			NumEscortModes = 0x2,
		};
	}

	namespace DataStreamer
	{
		enum STREAM_STATE
		{
			STATE_ERROR = 0x0,
			STATE_EMPTY = 0x1,
			STATE_LOAD_QUEUED = 0x2,
			STATE_LOADING = 0x3,
			STATE_FIXUP_DELAY = 0x4,
			STATE_RESOURCE_FIXUP = 0x5,
			STATE_ACTIVE = 0x6,
			STATE_DEACTIVATING = 0x7,
			STATE_COUNT = 0x8,
		};

		enum PRIORITY
		{
			VERY_HIGH_PRIORITY = 0x4000,
			HIGH_PRIORITY = 0x3000,
			HIGH_ANIM_PRIORITY = 0x2800,
			DEFAULT_PRIORITY = 0x2000,
			DEFAULT_ANIM_PRIORITY = 0x2000,
			LOW_PRIORITY = 0x1000,
			VERY_LOW_PRIORITY = 0x0,
		};
	}

	enum CollisionGeomFlags
	{
		CGF_STATIC = 0x1,
		CGF_DYNAMIC = 0x2,
		CGF_ANIMATED = 0x4,
		CGF_BOX_INERTIA = 0x8,
	};

	enum CollisionGeomType
	{
		CGT_MOPP = 0x0,
		CGT_CONVEX_VERTS = 0x1,
		CGT_RUNTIME = 0x2,
		CGT_SHAPELIST_MOPP = 0x3,
		CGT_SHAPELIST = 0x4,
		CGT_BOX = 0x5,
		CGT_CYLINDER = 0x6,
		CGT_SPHERE = 0x7,
		CGT_CAPSULE = 0x8,
	};

	enum eFractureConnectivity
	{
		FC_NONE = 0x0,
		FC_AUTO_BY_CONTACT = 0x1,
	};

	enum eHighlightModeEnum
	{
		eHIGHLIGHT_MODE_NONE = 0x0,
		eHIGHLIGHT_MODE_EXPLODABLE = 0x1,
	};

	enum eHowSpawned
	{
		FromScript = 0x0,
		FromRegion = 0x1,
		FromPoint = 0x2,
		FromNetwork = 0x3,
	};

	enum ePedType
	{
		AmbientPed = 0x1,
		ScriptedPed = 0x2,
	};

	namespace Parkour
	{
		enum CheckFlags
		{
			CHECK_PARKOUR = 0x1,
			CHECK_LEDGE = 0x2,
			CHECK_FENCE = 0x4,
			CHECK_VAULT = 0x8,
			CHECK_RAIL = 0x10,
			CHECK_WALL = 0x20,
			CHECK_LEAP = 0x40,
			CHECK_DROPOFF = 0x80,
			CHECK_ACTION_HIJACK_CLIMB = 0x100,
			CHECK_COVER = 0x200,
			CHECK_NOT_VEHICLE = 0x400,
		};
	}

	namespace PedSpawningInfo
	{
		enum eActiveStatus
		{
			Inactive = 0x0,
			Active = 0x1,
			ExtraLowPower = 0x2,
			NormalSuspend = 0x3,
			NetFull = 0x4,
			NetProxy = 0x5,
			eActiveStatus_Count = 0x6,
		};

		enum eDrawList
		{
			DrawList_None = 0x0,
			DrawList_Draw = 0x1,
			DrawList_NoDraw = 0x2,
		};
	}

	namespace PhysicsVehicle
	{
		enum Lod
		{
			LOD_UNINITIALIZED = 0x0,
			LOD_LOW = 0x1,
			LOD_MEDIUM = 0x2,
			LOD_HIGH = 0x3,
			LOD_NIS = 0x4,
			LOD_RESOURCES_UNLOADED = 0x5,
		};
	}

	enum eLODSetting
	{
		LOD_SETTING_LOW = 0x0,
		LOD_SETTING_NORMAL = 0x1,
		LOD_SETTING_HIGH = 0x2,
		LOD_SETTING_EXTREME = 0x3,
		NUM_LOD_SETTING = 0x4,
	};

	enum eAIEmotion
	{
		eAI_EMOTION_NONE = 0x0,
		eAI_EMOTION_SCARED = 0x1,
		eAI_EMOTION_AWARE = 0x2,
		eAI_EMOTION_INTERESTED = 0x3,
		eAI_EMOTION_PANIC = 0x4,
		eAI_EMOTION_SURPRISED = 0x5,
		eAI_EMOTION_NEUTRAL = 0x6,
		eAI_EMOTION_AGGRESSIVE = 0x7,
		eAI_EMOTION_HAPPY = 0x8,
		eAI_EMOTION_SAD = 0x9,
		eAI_EMOTION_ANGRY = 0xA,
		eAI_EMOTION_COCKY = 0xB,
		eAI_EMOTION_STERN = 0xC,
		NUM_AI_EMOTIONS = 0xD,
	};

	enum eAIObjective
	{
		eAI_OBJECTIVE_NONE = 0x0,
		eAI_OBJECTIVE_ATTACK_TARGET = 0x1,
		eAI_OBJECTIVE_ATTACK_NEARBY_TARGET = 0x2,
		eAI_OBJECTIVE_ATTACK_WHEN_SEE_TARGET = 0x3,
		eAI_OBJECTIVE_ATTACK_WHEN_STEALTH_TARGET_SPOTTED = 0x4,
		eAI_OBJECTIVE_ATTACK_USING_COVER = 0x5,
		eAI_OBJECTIVE_ATTACK_IN_SCRIPTED_VEHICLE = 0x6,
		eAI_OBJECTIVE_SHOOT_AT_MARKER = 0x7,
		eAI_OBJECTIVE_FLEE = 0x8,
		eAI_OBJECTIVE_FLEE_SPREAD_PANIC = 0x9,
		eAI_OBJECTIVE_FORCE_ENTER_COVER = 0xA,
		eAI_OBJECTIVE_RUN_LATERALLY_FROM_TARGET = 0xB,
		eAI_OBJECTIVE_INVESTIGATE_TARGET = 0xC,
		eAI_OBJECTIVE_PURSUIT_TARGET = 0xD,
		eAI_OBJECTIVE_FOLLOW_TARGET = 0xE,
		eAI_OBJECTIVE_FACE_TARGET = 0xF,
		eAI_OBJECTIVE_FACE_TARGET_WHILE_SCARED = 0x10,
		eAI_OBJECTIVE_BE_ALLY = 0x11,
		eAI_OBJECTIVE_GET_IN_VEHICLE = 0x12,
		eAI_OBJECTIVE_GET_OUT_OF_VEHICLE = 0x13,
		eAI_OBJECTIVE_BE_INTIMIDATED = 0x14,
		eAI_OBJECTIVE_PATHFIND_TO_SELECTED_OBJECT = 0x15,
		eAI_OBJECTIVE_HIJACK_VEHICLE = 0x16,
		eAI_OBJECTIVE_IDLE = 0x17,
		eAI_OBJECTIVE_MOVE_AWAY = 0x18,
		eAI_OBJECTIVE_RUN_AWAY = 0x19,
		eAI_OBJECTIVE_GRAB_AND_HOLD = 0x1A,
		eAI_OBJECTIVE_DUCK_AND_COVER = 0x1B,
		eAI_OBJECTIVE_DENOUEMENT = 0x1C,
		eAI_OBJECTIVE_WEAPON_PICKUP = 0x1D,
		eAI_OBJECTIVE_COMBAT_DUMMY = 0x1E,
		eAI_OBJECTIVE_PATHFIND_TO_POINT_WITH_BREAKOUT = 0x1F,
		eAI_OBJECTIVE_COMBAT_FAST_TALK = 0x20,
		eAI_OBJECTIVE_ATTACK_SUCKERPUNCH_TARGET = 0x21,
		eAI_OBJECTIVE_ROB_TARGET = 0x22,
		eAI_OBJECTIVE_PATDOWN_TARGET = 0x23,
		NUM_AI_OBJECTIVES = 0x24,
	};

	enum eAttackPhaseEnum
	{
		eATTACK_PHASE_INVALID = 0x0,
		eATTACK_PHASE_EXECUTION = 0x1,
		eATTACK_PHASE_COLLISION = 0x2,
		eATTACK_PHASE_RECOVERY = 0x3,
		NUM_ATTACK_PHASES = 0x4,
	};

	enum eCharacterActionRequestEnum
	{
		eCHARACTER_ACTION_REQUEST_ACTIVE = 0x0,
		eCHARACTER_ACTION_REQUEST_CANCEL = 0x1,
		eCHARACTER_ACTION_REQUEST_INVALID = 0x4,
		eCHARACTER_ACTION_REQUEST_NONE = 0x5,
		eCHARACTER_ACTION_REQUEST_ACTION = 0x7,
		eCHARACTER_ACTION_REQUEST_GRAB = 0x8,
		eCHARACTER_ACTION_REQUEST_JUMP = 0xA,
		eCHARACTER_ACTION_REQUEST_JIANGSHIDISABLE = 0xB,
		eCHARACTER_ACTION_REQUEST_FLIPOVER = 0xD,
		eCHARACTER_ACTION_REQUEST_ATTACK = 0xF,
		eCHARACTER_ACTION_REQUEST_ATTACK2 = 0x10,
		eCHARACTER_ACTION_REQUEST_WEAPON = 0x11,
		eCHARACTER_ACTION_REQUEST_RELOAD = 0x12,
		eCHARACTER_ACTION_REQUEST_DISARM = 0x13,
		eCHARACTER_ACTION_REQUEST_AVOID = 0x14,
		eCHARACTER_ACTION_REQUEST_VAULT = 0x15,
		eCHARACTER_ACTION_REQUEST_COWER = 0x16,
		eCHARACTER_ACTION_REQUEST_FLEE = 0x17,
		eCHARACTER_ACTION_REQUEST_SURRENDER = 0x18,
		eCHARACTER_ACTION_REQUEST_CROUCH = 0x1A,
		eCHARACTER_ACTION_REQUEST_RUNNINGATTACK = 0x1B,
		eCHARACTER_ACTION_REQUEST_VAULT_SUCCESS = 0x1D,
		eCHARACTER_ACTION_REQUEST_VAULT_FAIL = 0x1E,
		eCHARACTER_ACTION_REQUEST_ALERT = 0x32,
		eCHARACTER_ACTION_REQUEST_SPRINT = 0x37,
		eCHARACTER_ACTION_REQUEST_JOG = 0x38,
		eCHARACTER_ACTION_REQUEST_WALK = 0x39,
		eCHARACTER_ACTION_REQUEST_FREERUN = 0x3A,
		eCHARACTER_ACTION_REQUEST_STEER_RIGHT = 0x40,
		eCHARACTER_ACTION_REQUEST_STEER_LEFT = 0x41,
		eCHARACTER_ACTION_REQUEST_STEER_NEUTRAL = 0x42,
		eCHARACTER_ACTION_REQUEST_COMBAT_STANCE = 0xC1,
	};

	enum eCharacterTypeEnum
	{
		eCHARACTER_TYPE_INVALID = 0x0,
		eCHARACTER_TYPE_PLAYER = 0x1,
		eCHARACTER_TYPE_AMANDA = 0x2,
		eCHARACTER_TYPE_PEDESTRIAN = 0x3,
		eCHARACTER_TYPE_SHOPKEEPER = 0x4,
		eCHARACTER_TYPE_THUG = 0x5,
		eCHARACTER_TYPE_JACKIE = 0x6,
		eCHARACTER_TYPE_WAITRESS = 0x7,
		eCHARACTER_TYPE_BARTENDER = 0x8,
		eCHARACTER_TYPE_BOUNCER = 0x9,
		eCHARACTER_TYPE_POLICE_VARIANT1 = 0xA,
		eCHARACTER_TYPE_POLICE_VARIANT2 = 0xB,
		eCHARACTER_TYPE_POLICE_VARIANT3 = 0xC,
		eCHARACTER_TYPE_POLICE_VARIANT4 = 0xD,
		eCHARACTER_TYPE_POLICE_SWAT = 0xE,
		eCHARACTER_TYPE_NET_REMOTE_PLAYER = 0xF,
		eCHARACTER_TYPE_BENNY = 0x10,
		eCHARACTER_TYPE_DIRTY_MING = 0x11,
		eCHARACTER_TYPE_MRS_CHU = 0x12,
		eCHARACTER_TYPE_SS_WORKER = 0x13,
		eCHARACTER_TYPE_PED_DRUNK = 0x14,
		eCHARACTER_TYPE_PED_JUNKIE = 0x15,
		eCHARACTER_TYPE_PED_FAST = 0x16,
		eCHARACTER_TYPE_PED_SLOW = 0x17,
		eCHARACTER_TYPE_PED_SEXY = 0x18,
		eCHARACTER_TYPE_PED_ELDERLY = 0x19,
		eCHARACTER_TYPE_BEGGAR = 0x1A,
		eCHARACTER_TYPE_METER_MAID = 0x1B,
		eCHARACTER_TYPE_THIEF = 0x1C,
		eCHARACTER_TYPE_TIFFANY = 0x1D,
		eCHARACTER_TYPE_SIFU = 0x1E,
		eCHARACTER_TYPE_MARTIAL_ARTS_STUDENT = 0x1F,
		eCHARACTER_TYPE_ROOSTER = 0x20,
		eCHARACTER_TYPE_EMT = 0x21,
		eCHARACTER_TYPE_VALET = 0x22,
		eCHARACTER_TYPE_TONG = 0x23,
		eCHARACTER_TYPE_COOK = 0x24,
		eCHARACTER_TYPE_UNCLE_PO = 0x25,
		eCHARACTER_TYPE_DOGEYES = 0x26,
		eCHARACTER_TYPE_ZI_WAI = 0x27,
		eCHARACTER_TYPE_DLC_ELITE_GHOUL = 0x28,
		eCHARACTER_TYPE_DLC_JIANG_SHI = 0x29,
		eCHARACTER_TYPE_DLC_HAPPY_CAT = 0x2A,
		NUM_CHARACTER_TYPES = 0x2B,
	};

	enum eCharacterCollisionMode
	{
		CP_INVALID = 0x0,
		CP_WALK = 0x1,
		CP_CROUCH = 0x2,
		CP_CRAWL = 0x3,
		CP_DRIVING = 0x4,
		CP_ENTER_EXIT_VEHICLE = 0x5,
		CP_DISABLED = 0x6,
		CP_SITTING = 0x7,
		CP_COMBAT = 0x8,
		CP_DEAD = 0x9,
		CP_GRAPPLE = 0xA,
		CP_GRAPPLE_SMALL = 0xB,
		CP_COVER = 0xC,
		CP_FREERUN = 0xD,
		CP_NUM_SHAPES = 0xE,
	};

	enum eCoverPopoutSideEnum
	{
		ePOPOUT_SIDE_NONE = 0x0,
		ePOPOUT_SIDE_LEFT = 0x1,
		ePOPOUT_SIDE_RIGHT = 0x2,
		ePOPOUT_SIDE_TOP = 0x3,
		NUM_COVER_POPOUT_SIDE_TYPES = 0x4,
	};

	enum eFactionClassEnum
	{
		FACTION_INVALID = 0x0,
		FACTION_INDIFFERENT = 0x1,
		FACTION_PLAYER = 0x2,
		FACTION_LAW = 0x3,
		FACTION_TRIAD_WINSTON = 0x4,
		FACTION_TRIAD_DOGEYES = 0x5,
		FACTION_TRIAD_SONNY = 0x6,
		FACTION_TRIAD_JIIANG = 0x7,
		FACTION_TRIAD_CHEUK = 0x8,
		FACTION_TRIAD_TWOCHIN = 0x9,
		FACTION_TRIAD_GENERIC = 0xA,
		FACTION_TRIAD_WATERSTREET = 0xB,
		FACTION_TRIAD_18K = 0xC,
		FACTION_TRIAD_DOGBOYS = 0xD,
		FACTION_TRIAD_SUNONYEE = 0xE,
		FACTION_TRIAD_LEE = 0xF,
		FACTION_BOUNCER = 0x10,
		FACTION_INNOCENT = 0x11,
		FACTION_STUDENT = 0x12,
		FACTION_AMBIENT_AGGRESSIVE = 0x13,
		FACTION_AMBIENT_GROUP_1 = 0x14,
		FACTION_AMBIENT_GROUP_2 = 0x15,
		FACTION_AMBIENT_GROUP_3 = 0x16,
		FACTION_AMBIENT_GROUP_4 = 0x17,
		FACTION_NETWORK_TEAM_1 = 0x18,
		FACTION_NETWORK_TEAM_2 = 0x19,
		FACTION_NETWORK_TEAM_3 = 0x1A,
		FACTION_NETWORK_TEAM_4 = 0x1B,
		FACTION_NETWORK_TEAM_5 = 0x1C,
		FACTION_NETWORK_TEAM_6 = 0x1D,
		FACTION_NETWORK_TEAM_7 = 0x1E,
		FACTION_NETWORK_TEAM_8 = 0x1F,
		FACTION_HOSTILE_SPECIAL_1 = 0x20,
		FACTION_HOSTILE_SPECIAL_2 = 0x21,
		FACTION_ALLIED_SPECIAL_1 = 0x22,
		FACTION_ALLIED_SPECIAL_2 = 0x23,
		FACTION_LAW_HOSTILE = 0x24,
		FACTION_ROOSTER1 = 0x25,
		FACTION_ROOSTER2 = 0x26,
		NUM_FACTIONS = 0x27,
	};

	enum eFactionStandingEnum
	{
		FACTIONSTANDING_ALLIED = 0x0,
		FACTIONSTANDING_INDIFFERENT = 0x1,
		FACTIONSTANDING_HOSTILE = 0x2,
		FACTIONSTANDING_SCARED = 0x3,
		NUM_FACTIONSTANDINGS = 0x4,
	};

	enum eFightingClassEnum
	{
		eFIGHTING_CLASS_INVALID = 0x0,
		eFIGHTING_CLASS_NONE = 0x1,
		eFIGHTING_CLASS_NON_COMBATANT = 0x2,
		eFIGHTING_CLASS_STRIKER = 0x3,
		eFIGHTING_CLASS_STRIKER_QUICK = 0x4,
		eFIGHTING_CLASS_STRIKER_BRAWLER = 0x5,
		eFIGHTING_CLASS_GRAPPLER = 0x6,
		eFIGHTING_CLASS_TUTORIAL = 0x7,
		eFIGHTING_CLASS_ENFORCER = 0x8,
		eFIGHTING_CLASS_ELITE = 0x9,
		NUM_FIGHTING_CLASSES = 0xA,
	};

	enum eFocusModeEnum
	{
		eFOCUS_MODE_NONE = 0x0,
		eFOCUS_MODE_LOCKED = 0x1,
		eFOCUS_MODE_LOCKED_SOFT = 0x2,
		eFOCUS_MODE_FREE_AIMING = 0x3,
		eFOCUS_MODE_FREE_AIMING_LOCKED = 0x4,
		NUM_FOCUS_MODES = 0x5,
	};

	enum eGenderEnum
	{
		eGENDER_INVALID = 0x0,
		eGENDER_MALE = 0x1,
		eGENDER_FEMALE = 0x2,
		NUM_GENDERS = 0x3,
	};

	enum eHeatEventEnum
	{
		eHEATEVENT_NONE = 0x0,
		eHEATEVENT_INTIMIDATION = 0x1,
		eHEATEVENT_ASSAULT_MELEE_PEDESTRIAN = 0x2,
		eHEATEVENT_ASSAULT_MELEE_COP = 0x3,
		eHEATEVENT_ASSAULT_WEAPON_PEDESTRIAN = 0x4,
		eHEATEVENT_ASSAULT_WEAPON_COP = 0x5,
		eHEATEVENT_MANSLAUGHTER_PEDESTRIAN = 0x6,
		eHEATEVENT_MANSLAUGHTER_COP = 0x7,
		eHEATEVENT_GANG_FIGHT = 0x8,
		eHEATEVENT_WAVE_WEAPON = 0x9,
		eHEATEVENT_FIRE_WEAPON = 0xA,
		eHEATEVENT_WRECKLESS_DRIVING = 0xB,
		eHEATEVENT_ASSAULT_VEHICLE_PEDESTRIAN = 0xC,
		eHEATEVENT_ASSAULT_VEHICLE_COP = 0xD,
		eHEATEVENT_MANSLAUGHTER_VEHICLE_PEDESTRIAN = 0xE,
		eHEATEVENT_MANSLAUGHTER_VEHICLE_COP = 0xF,
		eHEATEVENT_VEHICLE_HIJACK = 0x10,
		eHEATEVENT_GRAPPLE_OTHER = 0x11,
		eHEATEVENT_GRAPPLE_COP = 0x12,
		eHEATEVENT_VEHICLE_COLLISION_OTHER = 0x13,
		eHEATEVENT_VEHICLE_COLLISION_COP = 0x14,
		eHEATEVENT_VEHICLE_TIRE_HIT_OTHER = 0x15,
		eHEATEVENT_VEHICLE_TIRE_HIT_COP = 0x16,
		eHEATEVENT_KIDNAP = 0x17,
		eHEATEVENT_EXPLOSION = 0x18,
		eHEATEVENT_RESIST_ARREST = 0x19,
		NUM_HEATEVENTS = 0x1A,
	};

	enum eHeatLevelEnum
	{
		HEATLEVEL_NONE = 0x0,
		HEATLEVEL_ONE = 0x1,
		HEATLEVEL_TWO = 0x2,
		HEATLEVEL_THREE = 0x3,
		HEATLEVEL_FOUR = 0x4,
		HEATLEVEL_FIVE = 0x5,
		NUM_HEAT_LEVELS = 0x6,
	};

	enum eInteriors
	{
		INTERIOR_NONE = 0x0,
		INTERIOR_SWEATSHOP = 0x1,
		INTERIOR_BAMBAM = 0x2,
		INTERIOR_HOSPITAL = 0x3,
		INTERIOR_VIVIENNE = 0x4,
		INTERIOR_RIVALBOSS = 0x5,
		INTERIOR_PENDREWHQ = 0x6,
		INTERIOR_KARAOKE = 0x7,
		INTERIOR_STRIP01 = 0x8,
		INTERIOR_STRIP02 = 0x9,
		INTERIOR_LOADING01 = 0xA,
		INTERIOR_SMILESHQ = 0xB,
		INTERIOR_BANQUET = 0xC,
		INTERIOR_FIFI = 0xD,
		INTERIOR_CHUREST = 0xE,
		INTERIOR_SAFEHOUSEAB = 0xF,
		INTERIOR_SAFEHOUSECT = 0x10,
		INTERIOR_SAFEHOUSEKT = 0x11,
		INTERIOR_SAFEHOUSENP = 0x12,
		INTERIOR_CTPENTHOUSE = 0x13,
		INTERIOR_DOJONP = 0x14,
		INTERIOR_MANSION = 0x15,
		INTERIOR_GAMBLINGDENCT = 0x16,
		INTERIOR_GAMBLINGDENNP = 0x17,
		INTERIOR_HIGHWAY = 0x18,
		INTERIOR_FISHMARKET = 0x19,
		NUM_INTERIORS = 0x1A,
	};

	enum eInventoryEquipSlot
	{
		eINVENTORY_EQUIP_SLOT_RIGHT_HAND = 0x0,
		eINVENTORY_EQUIP_SLOT_LEFT_HAND = 0x1,
		eINVENTORY_EQUIP_SLOT_HAT = 0x2,
		eINVENTORY_EQUIP_SLOT_GLASSES = 0x3,
		eINVENTORY_EQUIP_SLOT_STOWED_1H = 0x4,
		eINVENTORY_EQUIP_SLOT_STOWED_2H = 0x5,
		NUM_INVENTORY_EQUIP_SLOTS = 0x6,
	};

	enum eInventoryItemEnum
	{
		eINVENTORY_ITEM_INVALID = 0x0,
		eINVENTORY_ITEM_EMPTY_POP_CAN = 0x1,
		eINVENTORY_ITEM_BOTTLED_SODA = 0x2,
		eINVENTORY_ITEM_EMPTY_BEER_BOTTLE = 0x3,
		eINVENTORY_ITEM_BATON = 0x4,
		eINVENTORY_ITEM_POLICE_BATON = 0x5,
		eINVENTORY_ITEM_PICKET_SIGN = 0x6,
		eINVENTORY_ITEM_BROOM_FULL = 0x7,
		eINVENTORY_ITEM_CLEAVER = 0x8,
		eINVENTORY_ITEM_KNIFE = 0x9,
		eINVENTORY_ITEM_STORM_SWORD = 0xA,
		eINVENTORY_ITEM_PEACHWOOD_SWORD = 0xB,
		eINVENTORY_ITEM_BROOM_PUSH = 0xC,
		eINVENTORY_ITEM_PARKINGCOMPUTER = 0xD,
		eINVENTORY_ITEM_UMBRELLA = 0xE,
		eINVENTORY_ITEM_LIONHEAD = 0xF,
		eINVENTORY_ITEM_NEWSPAPER = 0x10,
		eINVENTORY_ITEM_SHOPPING_BAG = 0x11,
		eINVENTORY_ITEM_PORK_BUN = 0x12,
		eINVENTORY_ITEM_FOODONSTICK_A = 0x13,
		eINVENTORY_ITEM_FOODONSTICK_B = 0x14,
		eINVENTORY_ITEM_NOODLE_BOWL = 0x15,
		eINVENTORY_ITEM_NOODLE_BOX = 0x16,
		eINVENTORY_ITEM_FISH_BALLS = 0x17,
		eINVENTORY_ITEM_SPICY_SQUID = 0x18,
		eINVENTORY_ITEM_DIM_SUM = 0x19,
		eINVENTORY_ITEM_ICE_CREAM = 0x1A,
		eINVENTORY_ITEM_ENERGY_DRINK = 0x1B,
		eINVENTORY_ITEM_HAPPY_ENDING = 0x1C,
		eINVENTORY_ITEM_HAPPY_ENDING_2 = 0x1D,
		eINVENTORY_ITEM_HAPPY_ENDING_3 = 0x1E,
		eINVENTORY_ITEM_HERBAL_TEA = 0x1F,
		eINVENTORY_ITEM_PISTOL_9MM = 0x20,
		eINVENTORY_ITEM_PISTOL_9MM_AMMO = 0x21,
		eINVENTORY_ITEM_PISTOL_SERVICE = 0x22,
		eINVENTORY_ITEM_PISTOL_SERVICE_AMMO = 0x23,
		eINVENTORY_ITEM_PISTOL_45CAL = 0x24,
		eINVENTORY_ITEM_PISTOL_45CAL_TAC = 0x25,
		eINVENTORY_ITEM_PISTOL_45CAL_AMMO = 0x26,
		eINVENTORY_ITEM_PISTOL_HITMAN = 0x27,
		eINVENTORY_ITEM_PISTOL_JUST_CAUSE = 0x28,
		eINVENTORY_ITEM_RIFLE_ASSAUL_TAC = 0x29,
		eINVENTORY_ITEM_RIFLE_ASSAULT = 0x2A,
		eINVENTORY_ITEM_RIFLE_ASSAULT_DLC = 0x2B,
		eINVENTORY_ITEM_RIFLE_ASSAULT_AMMO = 0x2C,
		eINVENTORY_ITEM_RIFLE_DEUS_EX = 0x2D,
		eINVENTORY_ITEM_RIFLE_GRENADE = 0x2E,
		eINVENTORY_ITEM_RIFLE_GRENADE_AMMO = 0x2F,
		eINVENTORY_ITEM_RIFLE_GRENADE_AMMO_GRENADE = 0x30,
		eINVENTORY_ITEM_RIFLE_TEAR_GAS = 0x31,
		eINVENTORY_ITEM_SHOTGUN_PUMP = 0x32,
		eINVENTORY_ITEM_SHOTGUN_PUMP_AMMO = 0x33,
		eINVENTORY_ITEM_SHOTGUN_ANTI_TAC = 0x34,
		eINVENTORY_ITEM_SHOTGUN_ANTIRIOT = 0x35,
		eINVENTORY_ITEM_SHOTGUN_ANTIRIOT_AMMO = 0x36,
		eINVENTORY_ITEM_SMG_MACHINE_PISTOL = 0x37,
		eINVENTORY_ITEM_SMG_MACHINE_PISTOL_AMMO = 0x38,
		eINVENTORY_ITEM_SMG_45CAL_TACLIG = 0x39,
		eINVENTORY_ITEM_SMG_45CAL_GOLD = 0x3A,
		eINVENTORY_ITEM_SMG_45CAL = 0x3B,
		eINVENTORY_ITEM_SMG_45CAL_AMMO = 0x3C,
		eINVENTORY_ITEM_ELECTRO_SHOCK = 0x3D,
		eINVENTORY_ITEM_CAR_TURRET = 0x3E,
		eINVENTORY_ITEM_MONKEY_KING_STAFF = 0x3F,
		eINVENTORY_ITEM_TEAPOT = 0x40,
		eINVENTORY_ITEM_CROWBAR = 0x41,
		eINVENTORY_ITEM_TIREIRON = 0x42,
		eINVENTORY_ITEM_WOODENCLUB = 0x43,
		eINVENTORY_ITEM_MONEY = 0x44,
		eINVENTORY_ITEM_DRUG_PACKET = 0x45,
		eINVENTORY_ITEM_GROCERYBAG = 0x46,
		eINVENTORY_ITEM_CONTACTCARD = 0x47,
		eINVENTORY_ITEM_GAMEGUITAR = 0x48,
		eINVENTORY_ITEM_SHOVEL = 0x49,
		eINVENTORY_ITEM_DEED_AB_01 = 0x4A,
		eINVENTORY_ITEM_DEED_KT_01 = 0x4B,
		eINVENTORY_ITEM_DEED_CN_01 = 0x4C,
		eINVENTORY_ITEM_PURSE = 0x4D,
		eINVENTORY_ITEM_PURSEHAND = 0x4E,
		eINVENTORY_ITEM_BRIEFCASE = 0x4F,
		eINVENTORY_ITEM_BRIBE_CHEAP = 0x50,
		eINVENTORY_ITEM_BRIBE_AVERAGE = 0x51,
		eINVENTORY_ITEM_BRIBE_EXPENSIVE = 0x52,
		eINVENTORY_ITEM_COCKTAIL = 0x53,
		eINVENTORY_ITEM_TAXI_RIDE = 0x54,
		eINVENTORY_ITEM_M_DEER_ANTLERS = 0x55,
		eINVENTORY_ITEM_M_PIT_VIPER = 0x56,
		eINVENTORY_ITEM_M_DBP = 0x57,
		eINVENTORY_ITEM_M_SHIRT = 0x58,
		eINVENTORY_ITEM_M_GOWN = 0x59,
		eINVENTORY_ITEM_M_NECKLACE = 0x5A,
		eINVENTORY_ITEM_M_PURSE = 0x5B,
		eINVENTORY_ITEM_M_PURSEHAND = 0x5C,
		eINVENTORY_ITEM_M_DRUGS_ILLEGAL = 0x5D,
		eINVENTORY_ITEM_M_DRUGS_PRESC = 0x5E,
		eINVENTORY_ITEM_M_BEER = 0x5F,
		eINVENTORY_ITEM_M_VIRILITY = 0x60,
		eINVENTORY_ITEM_M_APT_CENTRAL = 0x61,
		eINVENTORY_ITEM_M_APT_ABERDEEN = 0x62,
		eINVENTORY_ITEM_M_APT_KENNEDY = 0x63,
		eINVENTORY_ITEM_M_CAMBRIA_WATCH = 0x64,
		eINVENTORY_ITEM_EXTORT_CHEAP = 0x65,
		eINVENTORY_ITEM_EXTORT_AVERAGE = 0x66,
		eINVENTORY_ITEM_EXTORT_EXPENSIVE = 0x67,
		eINVENTORY_ITEM_HIJACKED_VEHICLE = 0x68,
		eINVENTORY_ITEM_RAGWIPING = 0x69,
		eINVENTORY_ITEM_CAMERA = 0x6A,
		eINVENTORY_ITEM_CIGARETTE = 0x6B,
		eINVENTORY_ITEM_CLIPBOARD = 0x6C,
		eINVENTORY_ITEM_LOCKTOOL = 0x6D,
		eINVENTORY_ITEM_HAT = 0x6E,
		eINVENTORY_ITEM_HELMET = 0x6F,
		eINVENTORY_ITEM_GLASSES = 0x70,
		eINVENTORY_ITEM_PAINTCAN = 0x71,
		eINVENTORY_ITEM_HAMMER = 0x72,
		eINVENTORY_ITEM_WINEBOTTLE = 0x73,
		eINVENTORY_ITEM_INCENSE = 0x74,
		eINVENTORY_ITEM_FLOWERS = 0x75,
		eINVENTORY_ITEM_BROCHURE = 0x76,
		eINVENTORY_ITEM_BROCHURESTACK = 0x77,
		eINVENTORY_ITEM_RAKE = 0x78,
		eINVENTORY_ITEM_CANEWALKING = 0x79,
		eINVENTORY_ITEM_SCRUBBRUSH = 0x7A,
		eINVENTORY_ITEM_SQUEEGEE = 0x7B,
		eINVENTORY_ITEM_STICKTREE = 0x7C,
		eINVENTORY_ITEM_STICKBAMBOO = 0x7D,
		eINVENTORY_ITEM_DRINKINGGLASS = 0x7E,
		eINVENTORY_ITEM_BIGHAT = 0x7F,
		eINVENTORY_ITEM_SUNGLASSES = 0x80,
		eINVENTORY_ITEM_HEADSETBOUNCER = 0x81,
		eINVENTORY_ITEM_BAR_BILL = 0x82,
		eINVENTORY_ITEM_FERRY_TICKET = 0x83,
		eINVENTORY_ITEM_TRANSIT_TICKET = 0x84,
		eINVENTORY_ITEM_COOKINGPAN = 0x85,
		eINVENTORY_ITEM_COOKINGPOT = 0x86,
		eINVENTORY_ITEM_WRENCH = 0x87,
		eINVENTORY_ITEM_BET_LOW = 0x88,
		eINVENTORY_ITEM_BET_STANDARD = 0x89,
		eINVENTORY_ITEM_BET_HIGH = 0x8A,
		eINVENTORY_ITEM_BROOMWEAPON = 0x8B,
		eINVENTORY_ITEM_BOX = 0x8C,
		eINVENTORY_ITEM_FISH_BOX = 0x8D,
		eINVENTORY_ITEM_FRUIT_BOX = 0x8E,
		eINVENTORY_ITEM_FLIERS = 0x8F,
		eINVENTORY_ITEM_MACHETETONG = 0x90,
		eINVENTORY_ITEM_CELLPHONE = 0x91,
		eINVENTORY_ITEM_COOKINGSPOON = 0x92,
		eINVENTORY_ITEM_COOKINGWOK = 0x93,
		eINVENTORY_ITEM_BULLPENIS = 0x94,
		eINVENTORY_ITEM_HANDGRINDER = 0x95,
		eINVENTORY_ITEM_PARAMEDICBAG = 0x96,
		eINVENTORY_ITEM_FISHWRAPPED = 0x97,
		eINVENTORY_ITEM_MEATWRAPPED = 0x98,
		eINVENTORY_ITEM_CYMBAL = 0x99,
		eINVENTORY_ITEM_FIREEXTINGUISHER = 0x9A,
		eINVENTORY_ITEM_PISTOL_50CAL_GOL = 0x9B,
		eINVENTORY_ITEM_PISTOL_50CAL_SIL = 0x9C,
		eINVENTORY_ITEM_PISTOL_50CAL_AMMO = 0x9D,
		eINVENTORY_ITEM_PUNCHINGPAD_L = 0x9E,
		eINVENTORY_ITEM_PUNCHINGPAD_R = 0x9F,
		eINVENTORY_ITEM_DUFFLEBAG = 0xA0,
		eINVENTORY_ITEM_GARBAGEBAG = 0xA1,
		eINVENTORY_ITEM_FISHTUNA = 0xA2,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_01 = 0xA3,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_02 = 0xA4,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_03 = 0xA5,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_04 = 0xA6,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_05 = 0xA7,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_01 = 0xA8,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_02 = 0xA9,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_03 = 0xAA,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_04 = 0xAB,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_05 = 0xAC,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_01 = 0xAD,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_02 = 0xAE,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_03 = 0xAF,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_04 = 0xB0,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_05 = 0xB1,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_01 = 0xB2,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_02 = 0xB3,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_03 = 0xB4,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_04 = 0xB5,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_05 = 0xB6,
		eINVENTORY_ITEM_PACKAGE_PAPER = 0xB7,
		eINVENTORY_ITEM_DLC_01 = 0xB8,
		eINVENTORY_ITEM_DLC_02 = 0xB9,
		eINVENTORY_ITEM_DLC_03 = 0xBA,
		eINVENTORY_ITEM_DLC_04 = 0xBB,
		eINVENTORY_ITEM_DLC_05 = 0xBC,
		eINVENTORY_ITEM_DLC_06 = 0xBD,
		eINVENTORY_ITEM_DLC_07 = 0xBE,
		eINVENTORY_ITEM_DLC_08 = 0xBF,
		eINVENTORY_ITEM_DLC_09 = 0xC0,
		eINVENTORY_ITEM_DLC_10 = 0xC1,
		eINVENTORY_ITEM_DLC_11 = 0xC2,
		eINVENTORY_ITEM_DLC_12 = 0xC3,
		eINVENTORY_ITEM_DLC_13 = 0xC4,
		eINVENTORY_ITEM_DLC_14 = 0xC5,
		eINVENTORY_ITEM_DLC_15 = 0xC6,
		eINVENTORY_ITEM_DLC_16 = 0xC7,
		eINVENTORY_ITEM_DLC_17 = 0xC8,
		eINVENTORY_ITEM_DLC_18 = 0xC9,
		eINVENTORY_ITEM_DLC_19 = 0xCA,
		eINVENTORY_ITEM_DLC_20 = 0xCB,
		eINVENTORY_ITEM_DLC_21 = 0xCC,
		eINVENTORY_ITEM_DLC_22 = 0xCD,
		eINVENTORY_ITEM_DLC_23 = 0xCE,
		eINVENTORY_ITEM_DLC_24 = 0xCF,
		eINVENTORY_ITEM_DLC_25 = 0xD0,
		NUM_INVENTORY_ITEMS = 0xD1,
	};

	enum ePropertyTypeEnum : uint32_t
	{
		ePROPERTY_TYPE_CHAR = 0x0,
		ePROPERTY_TYPE_SHORT = 0x1,
		ePROPERTY_TYPE_INT = 0x2,
		ePROPERTY_TYPE_INT64 = 0x3,
		ePROPERTY_TYPE_UCHAR = 0x5,
		ePROPERTY_TYPE_USHORT = 0x6,
		ePROPERTY_TYPE_UINT = 0x7,
		ePROPERTY_TYPE_UINT64 = 0x8,
		ePROPERTY_TYPE_BOOL = 0x9,
		ePROPERTY_TYPE_FLOAT = 0xA,
		ePROPERTY_TYPE_PCHAR = 0xC,
		ePROPERTY_TYPE_RANGED_FLOAT = 0xD,
		ePROPERTY_TYPE_RANGED_INT = 0xF,
		ePROPERTY_TYPE_VECTOR2 = 0x11,
		ePROPERTY_TYPE_VECTOR3 = 0x12,
		ePROPERTY_TYPE_VECTOR4 = 0x13,
		ePROPERTY_TYPE_SYMBOL = 0x16,
		ePROPERTY_TYPE_SYMBOL2 = 0x17,
		ePROPERTY_TYPE_SYMBOL3 = 0x18,
		ePROPERTY_TYPE_PROPERTY_LIST = 0x19,
		ePROPERTY_TYPE_PROPERTY_SET = 0x1A,
	};

	enum eSimObjectTypeEnum
	{
		eSIM_OBJ_TYPE_INVALID = 0x0,
		eSIM_OBJ_TYPE_CHARACTER = 0x1,
		eSIM_OBJ_TYPE_PICKUP = 0x2,
		eSIM_OBJ_TYPE_WEAPON = 0x3,
		eSIM_OBJ_TYPE_VEHICLE = 0x4,
		eSIM_OBJ_TYPE_INTERACTIVE_PROP = 0x5,
		NUM_SIM_OBJECT_TYPES = 0x6,
	};

	// This is custom!
	enum eSimObjectTypeEnum2
	{
		eSIM_OBJ_TYPE2_Invalid = 0, 
		eSIM_OBJ_TYPE2_AIPathMarker,
		eSIM_OBJ_TYPE2_AIJumpPoint,
		eSIM_OBJ_TYPE2_AIOutlineRegion,
		eSIM_OBJ_TYPE2_AISeedPoint,
		eSIM_OBJ_TYPE2_AudioEmitterMarker,
		eSIM_OBJ_TYPE2_AudioTriggerRegion,
		eSIM_OBJ_TYPE2_BoostRegion,
		eSIM_OBJ_TYPE2_Camera,
		eSIM_OBJ_TYPE2_CameraMarker,
		eSIM_OBJ_TYPE2_Character,
		eSIM_OBJ_TYPE2_Collectible,
		eSIM_OBJ_TYPE2_CombatRegion,
		eSIM_OBJ_TYPE2_CopRoadBlock,
		eSIM_OBJ_TYPE2_Director,
		eSIM_OBJ_TYPE2_Door,
		eSIM_OBJ_TYPE2_DynamicLight,
		eSIM_OBJ_TYPE2_FleeToPoint,
		eSIM_OBJ_TYPE2_FXSimComponent,
		eSIM_OBJ_TYPE2_HidingSpot,
		eSIM_OBJ_TYPE2_HijackReturn,
		eSIM_OBJ_TYPE2_InterestPoint,
		eSIM_OBJ_TYPE2_IrradianceVolume,
		eSIM_OBJ_TYPE2_Marker,
		eSIM_OBJ_TYPE2_MarkerProgressionTrigger,
		eSIM_OBJ_TYPE2_MarkerRaceStartingGrid,
		eSIM_OBJ_TYPE2_MeleeScriptSystem,
		eSIM_OBJ_TYPE2_ModelAsset,
		eSIM_OBJ_TYPE2_NISScriptSystem,
		eSIM_OBJ_TYPE2_ParkingSpot,
		eSIM_OBJ_TYPE2_Prefab,
		eSIM_OBJ_TYPE2_Prop,
		eSIM_OBJ_TYPE2_ReinforcementPoint,
		eSIM_OBJ_TYPE2_TrafficRegion,
		eSIM_OBJ_TYPE2_TriggerRegion,
		eSIM_OBJ_TYPE2_Turf,
		eSIM_OBJ_TYPE2_Vehicle,
		eSIM_OBJ_TYPE2_Weapon,
		eSIM_OBJ_TYPE2_WeaponSpawner,
		eSIM_OBJ_TYPE2_StartRegion,
		eSIM_OBJ_TYPE2_SpawnPoint,
		eSIM_OBJ_TYPE2_SpawnPointProgressionTrigger,
		eSIM_OBJ_TYPE2_SpawnRegion
	};

	enum eSimObjectVehicleTypeEnum : uint32_t
	{
		eSIM_OBJ_VEHICLE_TYPE_INVALID = 0x0,
		eSIM_OBJ_VEHICLE_TYPE_BIKE = 0x1,
		eSIM_OBJ_VEHICLE_TYPE_CAR = 0x2,
		eSIM_OBJ_VEHICLE_TYPE_BOAT = 0x3,
		eSIM_OBJ_VEHICLE_TYPE_VAN = 0x4,
		eSIM_OBJ_VEHICLE_TYPE_TRUCK = 0x5,
		eSIM_OBJ_VEHICLE_TYPE_SCOOTER = 0x6,
		eSIM_OBJ_VEHICLE_TYPE_MINIBUS = 0x7,
		eSIM_OBJ_VEHICLE_TYPE_DDBUS = 0x8,
		eSIM_OBJ_VEHICLE_TYPE_TRAM = 0x9,
		NUM_SIM_OBJECT_VEHICLE_TYPES = 0xA,
	};

	enum eSimObjectBoatTypeEnum
	{
		eSIM_OBJ_BOAT_TYPE_INVALID = 0x0,
		eSIM_OBJ_BOAT_TYPE_COMMERCIAL_BOAT = 0x1,
		eSIM_OBJ_BOAT_TYPE_FERRY = 0x2,
		eSIM_OBJ_BOAT_TYPE_JET_BOAT = 0x3,
		eSIM_OBJ_BOAT_TYPE_SAMPAN = 0x4,
		eSIM_OBJ_BOAT_TYPE_YACHT = 0x5,
		eSIM_OBJ_BOAT_TYPE_ZODIAC = 0x6,
		NUM_SIM_OBJECT_BOAT_TYPES = 0x7,
	};

	namespace StreamingMemory
	{
		enum DATA_TYPE
		{
			DATA_UNKNOWN = 0x0,
			DATA_GLOBAL_LOC = 0x1,
			DATA_ZONE_LOC = 0x2,
			DATA_SECTION_LOD = 0x3,
			DATA_SECTION_STD = 0x4,
			DATA_GAMEPLAY_GLOBAL = 0x5,
			DATA_GAMEPLAY_CELL = 0x6,
			DATA_WORLD_INIT = 0x7,
			DATA_UI = 0x8,
			DATA_LOCALIZATION = 0x9,
			DATA_ROADNETWORK = 0xA,
			DATA_ANIMATION = 0xB,
			DATA_TRUECROWD_RESOURCE = 0xC,
			DATA_TRUECROWD_TEXTURE_RESOURCE = 0xD,
			DATA_GAME_GLOBAL_TEXTURES = 0xE,
			DATA_CLOUDS = 0xF,
			DATA_SCRIPT = 0x10,
			DATA_TERRAIN = 0x11,
			DATA_PARTSDB_RESOURCE = 0x12,
			DATA_PARTSDB_TEXTURE_RESOURCE = 0x13,
			DATA_TURF = 0x14,
			DATA_TYPE_COUNT = 0x15,
		};
	}

	enum eTargetTypeEnum
	{
		eTARGET_TYPE_INVALID = 0x0,
		eTARGET_TYPE_SELF = 0x1,
		eTARGET_TYPE_ATTACKER = 0x2,
		eTARGET_TYPE_AIM_POSITION = 0x3,
		eTARGET_TYPE_VEHICLE_DRIVER = 0x4,
		eTARGET_TYPE_VEHICLE_PASSENGER = 0x5,
		eTARGET_TYPE_VEHICLE_PASSENGER2 = 0x6,
		eTARGET_TYPE_VEHICLE_PASSENGER3 = 0x7,
		eTARGET_TYPE_VEHICLE_PASSENGER4 = 0x8,
		eTARGET_TYPE_VEHICLE_ROLE_SWAP_TEMP = 0x9,
		eTARGET_TYPE_VEHICLE_CARGO1 = 0xA,
		eTARGET_TYPE_VEHICLE_CARGO2 = 0xB,
		eTARGET_TYPE_VEHICLE_CARGO3 = 0xC,
		eTARGET_TYPE_VEHICLE_PASSENGER_TRUNK = 0xD,
		eTARGET_TYPE_CLOSEST_PED = 0xE,
		eTARGET_TYPE_COVER_OBJECT = 0xF,
		eTARGET_TYPE_COVER_POPOUT = 0x10,
		eTARGET_TYPE_EQUIPPED = 0x11,
		eTARGET_TYPE_EQUIPPED_LEFT_HAND = 0x12,
		eTARGET_TYPE_EQUIPPED_HAT = 0x13,
		eTARGET_TYPE_EQUIPPED_GLASSES = 0x14,
		eTARGET_TYPE_FACING = 0x15,
		eTARGET_TYPE_FOCUS = 0x16,
		eTARGET_TYPE_GRAPPLE = 0x17,
		eTARGET_TYPE_LOOK_AT = 0x18,
		eTARGET_TYPE_POI_LOOK_AT = 0x19,
		eTARGET_TYPE_POI_USE = 0x1A,
		eTARGET_TYPE_POI_PARENT_OBJECT = 0x1B,
		eTARGET_TYPE_VEHICLE = 0x1C,
		eTARGET_TYPE_AI_OBJECTIVE = 0x1D,
		eTARGET_TYPE_TO_FOLLOW = 0x1E,
		eTARGET_TYPE_PLAYER = 0x1F,
		eTARGET_TYPE_SCRIPTED_MARKER = 0x20,
		eTARGET_TYPE_STIMULUS_PRODUCER = 0x21,
		eTARGET_TYPE_CONDITION_STIMULUS_PRODUCER = 0x22,
		eTARGET_TYPE_IGNORE_AVOIDANCE = 0x23,
		eTARGET_TYPE_LAST_THREAT = 0x24,
		eTARGET_TYPE_POINT_AT = 0x25,
		eTARGET_TYPE_ATTACKING = 0x26,
		eTARGET_TYPE_CONVERSATION = 0x27,
		eTARGET_TYPE_INTERACTIVE_PROP = 0x28,
		eTARGET_TYPE_PICKUP_ITEM = 0x29,
		eTARGET_TYPE_STOWED_WEAPON = 0x2A,
		eTARGET_TYPE_STOWED_2H_WEAPON = 0x2B,
		eTARGET_TYPE_VEHICLE_ACTION_HIJACK = 0x2C,
		eTARGET_TYPE_VEHICLE_ACTION_HIJACK_POTENTIAL = 0x2D,
		eTARGET_TYPE_VEHICLE_CLOSEST_POINT = 0x2E,
		eTARGET_TYPE_CLOSEST_DOWNED_PED = 0x2F,
		eTARGET_TYPE_DIRECTIONAL = 0x30,
		eTARGET_TYPE_PHYSICAL = 0x31,
		eTARGET_TYPE_SOCIAL = 0x32,
		eTARGET_TYPE_CROWD_PUSH_PRIMARY = 0x33,
		eTARGET_TYPE_CROWD_PUSH_SECONDARY = 0x34,
		eTARGET_TYPE_ESCORT = 0x35,
		eTARGET_TYPE_OWNER = 0x36,
		eTARGET_TYPE_LAST_CREATED_OBJECT = 0x37,
		eTARGET_TYPE_SUBTARGET = 0x38,
		eTARGET_TYPE_TRANSIT = 0x39,
		eTARGET_TYPE_WORLD_EDITOR_SELECTED_OBJECT = 0x3A,
		eTARGET_TYPE_CRANE_CONTAINER_ATTACHED = 0x3B,
		eTARGET_TYPE_CRANE_CONTAINER_UNATTACHED = 0x3C,
		eTARGET_TYPE_MY_SPAWN_POINT = 0x3D,
		eTARGET_TYPE_GROUP_LEADER = 0x3E,
		eTARGET_TYPE_GROUP_MEMBER = 0x3F,
		eTARGET_TYPE_GROUP_MEMBER2 = 0x40,
		eTARGET_TYPE_GROUP_MEMBER3 = 0x41,
		eTARGET_TYPE_GROUP_MEMBER4 = 0x42,
		eTARGET_TYPE_GROUP_MEMBER_PAIRED = 0x43,
		eTARGET_TYPE_BEST_INTERACTION_POINT = 0x44,
		eTARGET_TYPE_INTERACTION_POINT0 = 0x45,
		eTARGET_TYPE_INTERACTION_POINT1 = 0x46,
		eTARGET_TYPE_INTERACTION_POINT2 = 0x47,
		eTARGET_TYPE_INTERACTION_POINT3 = 0x48,
		eTARGET_TYPE_INTERACTION_POINT4 = 0x49,
		eTARGET_TYPE_INTERACTION_POINT5 = 0x4A,
		eTARGET_TYPE_HIJACKABLE_VEHICLE = 0x4B,
		eTARGET_TYPE_SYNC = 0x4C,
		eTARGET_TYPE_BEST_MELEE_ATTACKER = 0x4D,
		eTARGET_TYPE_LAST_ATTACKED = 0x4E,
		eTARGET_TYPE_INTERACTION_OFFSET = 0x4F,
		eTARGET_TYPE_TRANSACTION = 0x50,
		eTARGET_TYPE_LAST_GRAPPLE = 0x51,
		eTARGET_TYPE_PROBE_LOW_L = 0x52,
		eTARGET_TYPE_PROBE_LOW_C = 0x53,
		eTARGET_TYPE_PROBE_LOW_R = 0x54,
		eTARGET_TYPE_PROBE_MID_L = 0x55,
		eTARGET_TYPE_PROBE_MID_C = 0x56,
		eTARGET_TYPE_PROBE_MID_R = 0x57,
		eTARGET_TYPE_PROBE_HIGH_L = 0x58,
		eTARGET_TYPE_PROBE_HIGH_C = 0x59,
		eTARGET_TYPE_PROBE_HIGH_R = 0x5A,
		NUM_TARGET_TYPES = 0x5B,
	};

	enum eParkourType
	{
		eParkourType_None = 0x0,
		eParkourType_Reluctant = 0x1,
		eParkourType_Normal = 0x2,
		NUM_PARKOUR_TYPES = 0x3,
	};

	enum VehicleEffectId
	{
		FX_NIGHTTIME = 0x0,
		FX_DAYTIME = 0x1,
		FX_PLAYERHEADLIGHTS = 0x2,
		FX_TRAFFICHEADLIGHTS = 0x3,
		FX_PLAYERHEADLIGHTFLARES = 0x4,
		FX_TRAFFICHEADLIGHTFLARES = 0x5,
		FX_BRAKELIGHTS = 0x6,
		FX_COPHEADLIGHTS = 0x7,
		FX_EXHAUST_CLEAN = 0x8,
		FX_EXHAUST_DIRTY = 0x9,
		FX_AIEXHAUST_CLEAN = 0xA,
		FX_AIEXHAUST_DIRTY = 0xB,
		FX_AILOWLODEXHAUST = 0xC,
		FX_REVERSE = 0xD,
		FX_LEFTTURN = 0xE,
		FX_RIGHTTURN = 0xF,
		FX_INTERIORLIGHTS = 0x10,
		FX_TAXILIGHTS = 0x11,
		FX_DISABLED = 0x12,
		FX_ENGINEDAMAGE = 0x13,
		FX_ENGINEBLOWN = 0x14,
		FX_DESTROYEDVEHICLE = 0x15,
		FX_SMOLDERING = 0x16,
		FX_DRAGGING = 0x17,
		FX_ROOFSLIDING = 0x18,
		FX_DESTRUCTFRONT = 0x19,
		FX_DESTRUCTMID = 0x1A,
		FX_DESTRUCTREAR = 0x1B,
		FX_DAMAGE = 0x1C,
		FX_WINDOWSHATTER = 0x1D,
		FX_WINDOWBREAKSM = 0x1E,
		FX_WINDOWBREAKMD = 0x1F,
		FX_WINDOWBREAKLG = 0x20,
		FX_SPRAY = 0x21,
		FX_AISPRAY = 0x22,
		FX_ENTERWATER = 0x23,
		FX_EXITWATER = 0x24,
		FX_WHEELEDVEHICLEJUMP = 0x25,
		FX_WHEELEDVEHICLEIMPACT = 0x26,
		EFFECT_TABLE_SIZE = 0x27,
	};

	enum eVehicleTrunkTypeEnum
	{
		eVEHICLE_TRUNK_TYPE_NONE = 0x0,
		eVEHICLE_TRUNK_TYPE_CAR_NARROW = 0x1,
		eVEHICLE_TRUNK_TYPE_CAR_STANDARD = 0x2,
		eVEHICLE_TRUNK_TYPE_CAR_WIDE = 0x3,
		eVEHICLE_TRUNK_TYPE_CAR_WIDER = 0x4,
		eVEHICLE_TRUNK_TYPE_VAN_STANDARD = 0x5,
		eVEHICLE_TRUNK_TYPE_VAN_WIDE = 0x6,
		eVEHICLE_TRUNK_TYPE_VAN_WIDER = 0x7,
		eVEHICLE_TRUNK_TYPE_VAN_NARROW = 0x8,
		NUM_VEHICLE_TRUNK_TYPES = 0x9,
	};
}