#pragma once

namespace UFG
{
	enum eInventoryEquipSlot
	{
		eINVENTORY_EQUIP_SLOT_RIGHT_HAND,
		eINVENTORY_EQUIP_SLOT_LEFT_HAND,
		eINVENTORY_EQUIP_SLOT_HAT,
		eINVENTORY_EQUIP_SLOT_GLASSES,
		eINVENTORY_EQUIP_SLOT_STOWED_1H,
		eINVENTORY_EQUIP_SLOT_STOWED_2H,
		NUM_INVENTORY_EQUIP_SLOTS
	};

	enum eInventoryItemEnum
	{
		eINVENTORY_ITEM_INVALID,
		eINVENTORY_ITEM_EMPTY_POP_CAN,
		eINVENTORY_ITEM_BOTTLED_SODA,
		eINVENTORY_ITEM_EMPTY_BEER_BOTTLE,
		eINVENTORY_ITEM_BATON,
		eINVENTORY_ITEM_POLICE_BATON,
		eINVENTORY_ITEM_PICKET_SIGN,
		eINVENTORY_ITEM_BROOM_FULL,
		eINVENTORY_ITEM_CLEAVER,
		eINVENTORY_ITEM_KNIFE,
		eINVENTORY_ITEM_STORM_SWORD,
		eINVENTORY_ITEM_PEACHWOOD_SWORD,
		eINVENTORY_ITEM_BROOM_PUSH,
		eINVENTORY_ITEM_PARKINGCOMPUTER,
		eINVENTORY_ITEM_UMBRELLA,
		eINVENTORY_ITEM_LIONHEAD,
		eINVENTORY_ITEM_NEWSPAPER,
		eINVENTORY_ITEM_SHOPPING_BAG,
		eINVENTORY_ITEM_PORK_BUN,
		eINVENTORY_ITEM_FOODONSTICK_A,
		eINVENTORY_ITEM_FOODONSTICK_B,
		eINVENTORY_ITEM_NOODLE_BOWL,
		eINVENTORY_ITEM_NOODLE_BOX,
		eINVENTORY_ITEM_FISH_BALLS,
		eINVENTORY_ITEM_SPICY_SQUID,
		eINVENTORY_ITEM_DIM_SUM,
		eINVENTORY_ITEM_ICE_CREAM,
		eINVENTORY_ITEM_ENERGY_DRINK,
		eINVENTORY_ITEM_HAPPY_ENDING,
		eINVENTORY_ITEM_HAPPY_ENDING_2,
		eINVENTORY_ITEM_HAPPY_ENDING_3,
		eINVENTORY_ITEM_HERBAL_TEA,
		eINVENTORY_ITEM_PISTOL_9MM,
		eINVENTORY_ITEM_PISTOL_9MM_AMMO,
		eINVENTORY_ITEM_PISTOL_SERVICE,
		eINVENTORY_ITEM_PISTOL_SERVICE_AMMO,
		eINVENTORY_ITEM_PISTOL_45CAL,
		eINVENTORY_ITEM_PISTOL_45CAL_TAC,
		eINVENTORY_ITEM_PISTOL_45CAL_AMMO,
		eINVENTORY_ITEM_PISTOL_HITMAN,
		eINVENTORY_ITEM_PISTOL_JUST_CAUSE,
		eINVENTORY_ITEM_RIFLE_ASSAUL_TAC,
		eINVENTORY_ITEM_RIFLE_ASSAULT,
		eINVENTORY_ITEM_RIFLE_ASSAULT_DLC,
		eINVENTORY_ITEM_RIFLE_ASSAULT_AMMO,
		eINVENTORY_ITEM_RIFLE_DEUS_EX,
		eINVENTORY_ITEM_RIFLE_GRENADE,
		eINVENTORY_ITEM_RIFLE_GRENADE_AMMO,
		eINVENTORY_ITEM_RIFLE_GRENADE_AMMO_GRENADE,
		eINVENTORY_ITEM_RIFLE_TEAR_GAS,
		eINVENTORY_ITEM_SHOTGUN_PUMP,
		eINVENTORY_ITEM_SHOTGUN_PUMP_AMMO,
		eINVENTORY_ITEM_SHOTGUN_ANTI_TAC,
		eINVENTORY_ITEM_SHOTGUN_ANTIRIOT,
		eINVENTORY_ITEM_SHOTGUN_ANTIRIOT_AMMO,
		eINVENTORY_ITEM_SMG_MACHINE_PISTOL,
		eINVENTORY_ITEM_SMG_MACHINE_PISTOL_AMMO,
		eINVENTORY_ITEM_SMG_45CAL_TACLIG,
		eINVENTORY_ITEM_SMG_45CAL_GOLD,
		eINVENTORY_ITEM_SMG_45CAL,
		eINVENTORY_ITEM_SMG_45CAL_AMMO,
		eINVENTORY_ITEM_ELECTRO_SHOCK,
		eINVENTORY_ITEM_CAR_TURRET,
		eINVENTORY_ITEM_MONKEY_KING_STAFF,
		eINVENTORY_ITEM_TEAPOT,
		eINVENTORY_ITEM_CROWBAR,
		eINVENTORY_ITEM_TIREIRON,
		eINVENTORY_ITEM_WOODENCLUB,
		eINVENTORY_ITEM_MONEY,
		eINVENTORY_ITEM_DRUG_PACKET,
		eINVENTORY_ITEM_GROCERYBAG,
		eINVENTORY_ITEM_CONTACTCARD,
		eINVENTORY_ITEM_GAMEGUITAR,
		eINVENTORY_ITEM_SHOVEL,
		eINVENTORY_ITEM_DEED_AB_01,
		eINVENTORY_ITEM_DEED_KT_01,
		eINVENTORY_ITEM_DEED_CN_01,
		eINVENTORY_ITEM_PURSE,
		eINVENTORY_ITEM_PURSEHAND,
		eINVENTORY_ITEM_BRIEFCASE,
		eINVENTORY_ITEM_BRIBE_CHEAP,
		eINVENTORY_ITEM_BRIBE_AVERAGE,
		eINVENTORY_ITEM_BRIBE_EXPENSIVE,
		eINVENTORY_ITEM_COCKTAIL,
		eINVENTORY_ITEM_TAXI_RIDE,
		eINVENTORY_ITEM_M_DEER_ANTLERS,
		eINVENTORY_ITEM_M_PIT_VIPER,
		eINVENTORY_ITEM_M_DBP,
		eINVENTORY_ITEM_M_SHIRT,
		eINVENTORY_ITEM_M_GOWN,
		eINVENTORY_ITEM_M_NECKLACE,
		eINVENTORY_ITEM_M_PURSE,
		eINVENTORY_ITEM_M_PURSEHAND,
		eINVENTORY_ITEM_M_DRUGS_ILLEGAL,
		eINVENTORY_ITEM_M_DRUGS_PRESC,
		eINVENTORY_ITEM_M_BEER,
		eINVENTORY_ITEM_M_VIRILITY,
		eINVENTORY_ITEM_M_APT_CENTRAL,
		eINVENTORY_ITEM_M_APT_ABERDEEN,
		eINVENTORY_ITEM_M_APT_KENNEDY,
		eINVENTORY_ITEM_M_CAMBRIA_WATCH,
		eINVENTORY_ITEM_EXTORT_CHEAP,
		eINVENTORY_ITEM_EXTORT_AVERAGE,
		eINVENTORY_ITEM_EXTORT_EXPENSIVE,
		eINVENTORY_ITEM_HIJACKED_VEHICLE,
		eINVENTORY_ITEM_RAGWIPING,
		eINVENTORY_ITEM_CAMERA,
		eINVENTORY_ITEM_CIGARETTE,
		eINVENTORY_ITEM_CLIPBOARD,
		eINVENTORY_ITEM_LOCKTOOL,
		eINVENTORY_ITEM_HAT,
		eINVENTORY_ITEM_HELMET,
		eINVENTORY_ITEM_GLASSES,
		eINVENTORY_ITEM_PAINTCAN,
		eINVENTORY_ITEM_HAMMER,
		eINVENTORY_ITEM_WINEBOTTLE,
		eINVENTORY_ITEM_INCENSE,
		eINVENTORY_ITEM_FLOWERS,
		eINVENTORY_ITEM_BROCHURE,
		eINVENTORY_ITEM_BROCHURESTACK,
		eINVENTORY_ITEM_RAKE,
		eINVENTORY_ITEM_CANEWALKING,
		eINVENTORY_ITEM_SCRUBBRUSH,
		eINVENTORY_ITEM_SQUEEGEE,
		eINVENTORY_ITEM_STICKTREE,
		eINVENTORY_ITEM_STICKBAMBOO,
		eINVENTORY_ITEM_DRINKINGGLASS,
		eINVENTORY_ITEM_BIGHAT,
		eINVENTORY_ITEM_SUNGLASSES,
		eINVENTORY_ITEM_HEADSETBOUNCER,
		eINVENTORY_ITEM_BAR_BILL,
		eINVENTORY_ITEM_FERRY_TICKET,
		eINVENTORY_ITEM_TRANSIT_TICKET,
		eINVENTORY_ITEM_COOKINGPAN,
		eINVENTORY_ITEM_COOKINGPOT,
		eINVENTORY_ITEM_WRENCH,
		eINVENTORY_ITEM_BET_LOW,
		eINVENTORY_ITEM_BET_STANDARD,
		eINVENTORY_ITEM_BET_HIGH,
		eINVENTORY_ITEM_BROOMWEAPON,
		eINVENTORY_ITEM_BOX,
		eINVENTORY_ITEM_FISH_BOX,
		eINVENTORY_ITEM_FRUIT_BOX,
		eINVENTORY_ITEM_FLIERS,
		eINVENTORY_ITEM_MACHETETONG,
		eINVENTORY_ITEM_CELLPHONE,
		eINVENTORY_ITEM_COOKINGSPOON,
		eINVENTORY_ITEM_COOKINGWOK,
		eINVENTORY_ITEM_BULLPENIS,
		eINVENTORY_ITEM_HANDGRINDER,
		eINVENTORY_ITEM_PARAMEDICBAG,
		eINVENTORY_ITEM_FISHWRAPPED,
		eINVENTORY_ITEM_MEATWRAPPED,
		eINVENTORY_ITEM_CYMBAL,
		eINVENTORY_ITEM_FIREEXTINGUISHER,
		eINVENTORY_ITEM_PISTOL_50CAL_GOL,
		eINVENTORY_ITEM_PISTOL_50CAL_SIL,
		eINVENTORY_ITEM_PISTOL_50CAL_AMMO,
		eINVENTORY_ITEM_PUNCHINGPAD_L,
		eINVENTORY_ITEM_PUNCHINGPAD_R,
		eINVENTORY_ITEM_DUFFLEBAG,
		eINVENTORY_ITEM_GARBAGEBAG,
		eINVENTORY_ITEM_FISHTUNA,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_01,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_02,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_03,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_04,
		eINVENTORY_ITEM_NP_SAFEHOUSEITEM_05,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_01,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_02,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_03,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_04,
		eINVENTORY_ITEM_CN_SAFEHOUSEITEM_05,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_01,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_02,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_03,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_04,
		eINVENTORY_ITEM_AB_SAFEHOUSEITEM_05,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_01,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_02,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_03,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_04,
		eINVENTORY_ITEM_KT_SAFEHOUSEITEM_05,
		eINVENTORY_ITEM_PACKAGE_PAPER,
		eINVENTORY_ITEM_DLC_01,
		eINVENTORY_ITEM_DLC_02,
		eINVENTORY_ITEM_DLC_03,
		eINVENTORY_ITEM_DLC_04,
		eINVENTORY_ITEM_DLC_05,
		eINVENTORY_ITEM_DLC_06,
		eINVENTORY_ITEM_DLC_07,
		eINVENTORY_ITEM_DLC_08,
		eINVENTORY_ITEM_DLC_09,
		eINVENTORY_ITEM_DLC_10,
		eINVENTORY_ITEM_DLC_11,
		eINVENTORY_ITEM_DLC_12,
		eINVENTORY_ITEM_DLC_13,
		eINVENTORY_ITEM_DLC_14,
		eINVENTORY_ITEM_DLC_15,
		eINVENTORY_ITEM_DLC_16,
		eINVENTORY_ITEM_DLC_17,
		eINVENTORY_ITEM_DLC_18,
		eINVENTORY_ITEM_DLC_19,
		eINVENTORY_ITEM_DLC_20,
		eINVENTORY_ITEM_DLC_21,
		eINVENTORY_ITEM_DLC_22,
		eINVENTORY_ITEM_DLC_23,
		eINVENTORY_ITEM_DLC_24,
		eINVENTORY_ITEM_DLC_25,
		NUM_INVENTORY_ITEMS
	};

	class InventoryItem
	{
	public:
		int m_iQuantity;
	};

	class InventoryComponent : public SimComponent, public qNode<InventoryComponent>
	{
	public:
		enum { _TypeUID = 0xAC000001 };

		struct EquipInfo
		{
			qSymbolUC mPropBoneUID;
			qSymbolUC mCharacterBoneUID;
			eTargetTypeEnum mEquipTarget;
		};

		struct EquipSlot
		{
			bool mCanDrop;
		};

		qFixedArray<EquipSlot, NUM_INVENTORY_EQUIP_SLOTS> m_EquipSlots;
		InventoryItem m_InventoryItems[NUM_INVENTORY_ITEMS];
		eInventoryItemEnum m_SellableItem;
		qSymbol m_SellableItemProp;
		bool m_InfiniteSellableItem;
		bool m_bCheatUnlimitedAmmo;
		bool m_bDebugDrawInventory;

		/* Static Functions */

		SDK_SINLINE bool Equip(SimObject* pSimObject, SimObject* pObjectToEquip) { return SDK_CALL_FUNC(bool, 0x527860, SimObject*, SimObject*)(pSimObject, pObjectToEquip); }

		/* Impl Functions */

		SDK_INLINE bool GetCanDrop(eInventoryEquipSlot slot) { return m_EquipSlots[slot].mCanDrop; }
		SDK_INLINE qSymbol GetSellableItemProp() { return m_SellableItemProp; }
		SDK_INLINE void SetCanDrop(eInventoryEquipSlot slot, bool canDrop) { m_EquipSlots[slot].mCanDrop = canDrop; }

		/* Functions */

		void AddInventoryList(qPropertyList* inventory_list) { SDK_CALL_FUNC(void, 0x520AB0, void*, qPropertyList*)(this, inventory_list); }
		char AddObjectToInventory(SimObject* pObject, bool bForceObjectToInventory) { return SDK_CALL_FUNC(char, 0x520C70, void*, SimObject*, bool)(this, pObject, bForceObjectToInventory); }
		bool AddQuantity(eInventoryItemEnum eInventoryItem, int iQuantity) { return SDK_CALL_FUNC(bool, 0x521290, void*, eInventoryItemEnum, int)(this, eInventoryItem, iQuantity); }
		bool Equip(SimObject* pObjectToEquip) { return SDK_CALL_FUNC(bool, 0x526F80, void*, SimObject*)(this, pObjectToEquip); }
		bool Equip(SimObject* pObjectToEquip, bool useEquipSlot, eInventoryEquipSlot inventoryEquipSlot) {
			return SDK_CALL_FUNC(bool, 0x526F90, void*, SimObject*, bool, eInventoryEquipSlot)(this, pObjectToEquip, useEquipSlot, inventoryEquipSlot);
		}
		eTargetTypeEnum GetSlotTarget(eInventoryEquipSlot slot) { return SDK_CALL_FUNC(eTargetTypeEnum, 0x52FCD0, eInventoryEquipSlot)(slot); }
		void RemoveObjectFromInventory(SimObject* pObject) { SDK_CALL_FUNC(void, 0x549120, void*, SimObject*)(this, pObject); }
		int RemoveQuantity(eInventoryItemEnum eInventoryItem, int iQuantity) { return SDK_CALL_FUNC(int, 0x5495C0, void*, eInventoryItemEnum, int)(this, eInventoryItem, iQuantity); }
		void ResetFromProperties(qPropertySet* pProps) { SDK_CALL_FUNC(void, 0x549E90, void*, qPropertySet*)(this, pProps); }
		void Stow(eInventoryEquipSlot sourceSlot, eInventoryEquipSlot destinationSlot) { SDK_CALL_FUNC(void, 0x552A40, void*, int, int)(this, sourceSlot, destinationSlot); }
		void UnEquip(eInventoryEquipSlot slot, bool bDeleteFromWorld) { SDK_CALL_FUNC(void, 0x557A40, void*, eInventoryEquipSlot, bool)(this, slot, bDeleteFromWorld); }
	};
	SDK_ASSERT_SIZEOF(InventoryComponent, 0x3B0);
}