#pragma once

namespace UFG
{
	enum CollisionLayers : i32
	{
		DEFAULT_LAYER,
		PLAYER_LAYER,
		NETWORK_PROXY_LAYER = PLAYER_LAYER,
		PLAYER_LAYER2,
		PLAYER_COMBAT_LAYER,
		PLAYER_DEAD_LAYER,
		PLAYER_ENTER_EXIT_VEHICLE_LAYER,
		PLAYER_SITTING_LAYER,
		RAGDOLL_LAYER,
		RAGDOLL_LAYER_2,
		TERRAIN_LAYER,
		DESTRUCTABLE_TERRAIN_LAYER,
		WHEELRAYCAST_LAYER,
		USER_RAYCAST_LAYER_1,
		USER_RAYCAST_LAYER_2,
		USER_RAYCAST_LAYER_3,
		USER_RAYCAST_LAYER_4,
		USER_RAYCAST_LAYER_5,
		USER_RAYCAST_LAYER_6,
		CAMERA_LAYER,
		LIGHT_DEBRIS_LAYER,
		HEAVY_DEBRIS_LAYER,
		NO_COLLISION_LAYER,
		VEHICLE_LAYER,
		WORLD_AVOIDANCE_LAYER,
		OBJECT_AVOIDANCE_LAYER,
		BULLET_LAYER,
		WEAPON_LAYER,
		BULLET_REACTION_LAYER,
		WATER_LAYER,
		SENSOR_COMPONENT_LAYER,
		CAMERA_BARRIER_LAYER,
		SEETHROUGH_SHOOTTHROUGH_LAYER,

		NUM_COLLISION_LAYERS,
		MAX_LAYERS = NUM_COLLISION_LAYERS,
	};
}