#pragma once

// Move this to appropriate file.
namespace UFG
{
	enum eAttackType
	{
		eATTACK_TYPE_MELEE,
		eATTACK_TYPE_RANGED,
		eATTACK_TYPE_DIRECT_FOLLOWERS,
		NUM_ATTACK_TYPES,
		eATTACK_TYPE_NONE = -1
	};

	enum eInCoverType
	{
		eIN_COVER_NO,
		eIN_COVER_YES,
		NUM_IN_COVER_TYPES
	};

	enum eCollisionAvoidanceType
	{
		eCOLLISION_AVOIDANCE_EVERYONE,
		eCOLLISION_AVOIDANCE_NOT_DEAD_GUYS,
		eCOLLISION_AVOIDANCE_NOT_ATTACK_TARGET_OR_DEAD_GUYS,
		eCOLLISION_AVOIDANCE_NOT_ATTACK_TARGET_OR_FORMATION_MEMBERS_OR_DEAD_GUYS,
		eCOLLISION_AVOIDANCE_NOT_INNOCENTS,
		eCOLLISION_AVOIDANCE_NOT_IGNORE_AVOIDANCE_TARGET,
		eCOLLISION_AVOIDANCE_FOR_PEDFORMATION_LEADER,
		eCOLLISION_AVOIDANCE_FOR_PEDFORMATION_FOLLOWER,
		eCOLLISION_AVOIDANCE_NO_ONE,
		NUM_COLLISION_AVOIDANCE_TYPES
	};

	enum eConstrainToSidewalks
	{
		eCONSTRAIN_TO_SIDEWALKS_YES,
		eCONSTRAIN_TO_SIDEWALKS_NO,
		NUM_CONSTRAIN_TO_SIDEWALKS_TYPES
	};
}

namespace UFG
{
	enum eAIEmotion
	{
		eAI_EMOTION_NONE,
		eAI_EMOTION_SCARED,
		eAI_EMOTION_AWARE,
		eAI_EMOTION_INTERESTED,
		eAI_EMOTION_PANIC,
		eAI_EMOTION_SURPRISED,
		eAI_EMOTION_NEUTRAL,
		eAI_EMOTION_AGGRESSIVE,
		eAI_EMOTION_HAPPY,
		eAI_EMOTION_SAD,
		eAI_EMOTION_ANGRY,
		eAI_EMOTION_COCKY,
		eAI_EMOTION_STERN,
		NUM_AI_EMOTIONS
	};
}