#pragma once

namespace UFG
{
	enum eStimulusType
	{
		eSTIMULUS_NONE,
		eSTIMULUS_COP_NEARBY,
		eSTIMULUS_PURCHASE,
		eSTIMULUS_PURCHASE_FAIL,
		eSTIMULUS_DANGEROUS_FLYING_OBJECT,
		eSTIMULUS_MELEE_ATTACK,
		eSTIMULUS_MELEE_ATTACK_NEAR_YOU,
		eSTIMULUS_MELEE_ATTACK_NO_HIT,
		eSTIMULUS_MELEE_ATTACK_CAR_DOORSLAM,
		eSTIMULUS_MELEE_FIGHT_VS_COMBATANT,
		eSTIMULUS_MELEE_FIGHT_VS_INNOCENT,
		eSTIMULUS_SAW_TARGET,
		eSTIMULUS_GUN_FIGHT,
		eSTIMULUS_DRAW_WEAPON,
		eSTIMULUS_FIRE_WEAPON,
		eSTIMULUS_FIRE_WEAPON_NEAR_YOU,
		eSTIMULUS_EXPLOSION,
		eSTIMULUS_SCARED_PEDESTRIAN,
		eSTIMULUS_INTERESTED_PEDESTRIAN,
		eSTIMULUS_DEAD_PERSON,
		eSTIMULUS_DYING_PERSON,
		eSTIMULUS_SPRINTING_PERSON,
		eSTIMULUS_IN_PURSUIT_PERSON,
		eSTIMULUS_STOP_AND_LOOK,
		eSTIMULUS_GUN_POINTED_AT_YOU,
		eSTIMULUS_GUN_POINTED_NEAR_YOU,
		eSTIMULUS_REQUEST_LISTEN,
		eSTIMULUS_REQUEST_TALK,
		eSTIMULUS_DANGEROUS_VEHICLE,
		eSTIMULUS_INTIMIDATE,
		eSTIMULUS_COMBAT_INTIMIDATE,
		eSTIMULUS_GROUP_INTIMIDATE,
		eSTIMULUS_INTIMIDATE_FAIL,
		eSTIMULUS_GREET,
		eSTIMULUS_WATCHED,
		eSTIMULUS_TAUNTED_HOSTILE_TARGET,
		eSTIMULUS_BEGAN_ATTACKING_HOSTILE_TARGET,
		eSTIMULUS_MOVEOUTOFWAY_NEAR,
		eSTIMULUS_MOVEOUTOFWAY_MED,
		eSTIMULUS_MOVEOUTOFWAY_FAR,
		eSTIMULUS_THUG_NEARBY,
		eSTIMULUS_KEEP_AWAY_FROM_THIS_AREA,
		eSTIMULUS_ATTACK_AS_FOLLOWER,
		eSTIMULUS_BUMPED,
		eSTIMULUS_VEHICLE_HORN,
		eSTIMULUS_VEHICLE_DAMAGED_BY_MELEE,
		eSTIMULUS_VEHICLE_HIT_PED,
		eSTIMULUS_VEHICLE_HIT_YOU,
		eSTIMULUS_VEHICLE_WRECKLESS,
		eSTIMULUS_HIGH_FACE,
		eSTIMULUS_LOW_FACE,
		eSTIMULUS_CARJACK,
		eSTIMULUS_CARJACK_YOU,
		eSTIMULUS_OBJECT_DESTROYE5,
		eSTIMULUS_OBJECT_SHEARED,
		eSTIMULUS_FACE_ME,
		eSTIMULUS_SOCIAL_CHARGE,
		eSTIMULUS_SOCIAL_INTERACTION_START,
		eSTIMULUS_SOCIAL_INTERACTION_END,
		eSTIMULUS_SOCIAL_MINIGAME_START,
		eSTIMULUS_SOCIAL_SUCCESS,
		eSTIMULUS_SOCIAL_FAILURE,
		eSTIMULUS_HAIL_CAB,
		eSTIMULUS_GROUP_MEMBER_ATTACKED,
		eSTIMULUS_GROUP_MEMBER_SCARED_BY_WEAPON,
		eSTIMULUS_CAR_HIT_CAR,
		eSTIMULUS_CAR_HIT_BUILDING,
		eSTIMULUS_CAR_HIT_MY_CAR,
		eSTIMULUS_BULLET_IMPACT,
		eSTIMULUS_IVE_BEEN_SHOT,
		eSTIMULUS_IVE_BEEN_SHOT_NEARBY,
		eSTIMULUS_VEHICLE_BURNOUT,
		eSTIMULUS_VEHICLE_SMOKE,
		eSTIMULUS_VEHICLE_FIRE,
		eSTIMULUS_COMBAT_TAUNT,
		eSTIMULUS_THROWN_OVER,
		eSTIMULUS_CRIME_SCENE,
		eSTIMULUS_PARKOUR_ACTION,
		eSTIMULUS_PARKOUR_SUCCESS,
		eSTIMULUS_PARKOUR_FAIL,
		eSTIMULUS_INTEREST_PICTURE,
		eSTIMULUS_INTEREST_WHISTLE,
		eSTIMULUS_INTEREST_DISGUST,
		eSTIMULUS_INTEREST_FUNNY,
		eSTIMULUS_INTEREST_AWE,
		eSTIMULUS_INTEREST_SCARY,
		eSTIMULUS_INTEREST_APPROACH,
		eSTIMULUS_CAR_PARKED_SIDEWALK,
		eSTIMULUS_FALLING_IMPACT,
		eSTIMULUS_FLYING_OBJECT_HIT_ME,
		eSTIMULUS_COMBAT_SHOCK,
		eSTIMULUS_AMBIENT_THUG_TAUNT,
		eSTIMULUS_KARAOKE_IN_PROGRESS,
		eSTIMULUS_KARAOKE_SINGING_BAD,
		eSTIMULUS_KARAOKE_SINGING_GOOD,
		eSTIMULUS_KARAOKE_SINGING_PERFECT,
		eSTIMULUS_POLICE_PURSUIT_FOOT,
		eSTIMULUS_POLICE_PURSUIT_VEHICLE,
		eSTIMULUS_INITIATE_SOCIAL_PURCHASE,
		eSTIMULUS_CAMERA,
		eSTIMULUS_POSSESS_STOLEN_PROPERTY,
		eSTIMULUS_STUNT_IMPRESSED,
		eSTIMULUS_STUNT_BLOWNAWAY,
		eSTIMULUS_STEALTH_GUARDSHOT,
		eSTIMULUS_STEALTH_GUARDMELEE,
		eSTIMULUS_STEALTH_GUNFIRENEARBY,
		eSTIMULUS_STEALTH_OBJECTBREAKING,
		eSTIMULUS_STEALTH_OBJECTMOVING,
		eSTIMULUS_STEALTH_JOGGING,
		eSTIMULUS_STEALTH_SOMETHING_FELL,
		eSTIMULUS_STEALTH_SPRINTING,
		eSTIMULUS_STEALTH_WALKING,
		eSTIMULUS_STEALTH_WATER_LANDING,
		eSTIMULUS_SITTING_PED_NEARBY,
		eSTIMULUS_SCRIPT_EXIT,
		eSTIMULUS_SOCIAL_COMBAT_FAST_TALK,
		NUM_STIMULUS_TYPES
	};

	class Stimulus : public Event
	{
	public:
		StimulusDescription m_Description;
		StimulusParameters m_StimulusParameters;
		qSafePointer<SimObject> m_pStimulusProducer;
		qStaticBitField<116> m_StimulusMask;
		qSafePointer<AIEntityComponent> m_pStimulusProducerAIEntityComponent;
		qSafePointer<RigidBodyComponent> m_pStimulusProducerRigidBodyComponent;
		qSafePointer<SimObjectCharacterPropertiesComponent> m_pStimulusProducerCharacterPropertiesComponent;
		qSafePointer<InventoryItemComponent> m_pStimulusProducerInventoryItemComponent;
		qSafePointer<TargetingSystemBaseComponent> m_pStimulusProducerTargetingSystemBaseComponent;
		qSafePointer<StimulusEmitterComponent> m_pStimulusProducerStimulusEmitterComponent;
		bool m_StimulusProducerInfoValid;
		qVector3 m_StimulusProducerPosition;
		qVector3 m_StimulusProducerVelocity;
		qVector3 m_StimulusProducerFacing;
		bool m_IsTargeted;
		qSafePointer<SimObject> m_pStimulusTarget;

		void Init(StimulusEmitterComponent* emitter, SimObject* stimulus_target) { SDK_CALL_FUNC(void, 0x366490, void*, StimulusEmitterComponent*, SimObject*)(this, emitter, stimulus_target); }
	};
}