#pragma once

namespace UFG
{
	enum eTicketBoothEnum
	{
		TICKETBOOTH_PLAYER_AIACTIONTREEUPDATE,
		TICKETBOOTH_CRITICAL_AIACTIONTREEUPDATE,
		TICKETBOOTH_NON_CRITICAL_AIACTIONTREEUPDATE,
		TICKETBOOTH_VEHICLE_AIACTIONTREEUPDATE,
		TICKETBOOTH_NON_CRITICAL_NAVCOMPONENT_POSTSTREAMING,
		TICKETBOOTH_CRITICAL_NAVCOMPONENT_POSTSTREAMING,
		TICKETBOOTH_KNOWLEDGEBASE_REFRESHHOSTILES,
		TICKETBOOTH_KNOWLEDGEBASE_UPDATE,
		TICKETBOOTH_PEDFORMATIONMANANGER_UPDATE,
		TICKETBOOTH_NAVLOCAL_GATHEROBSTACLE,
		NUM_TICKETBOOTHS
	};
}