#pragma once

namespace Illusion
{
	enum eStateParamValue
	{
		StateParamValue_CB_SceneryInstance = 34,
		StateParamValue_CB_FXOverrideSettings = 82,
		StateParamValue_CB_BeamSettings = 88,
	};

	enum eVertexSteamElementType
	{
		VERTEX_TYPE_FLOAT3 = 0x0,
		VERTEX_TYPE_FLOAT4 = 0x1,
		VERTEX_TYPE_HALF2 = 0x2,
		VERTEX_TYPE_UBYTE4 = 0x3,
		VERTEX_TYPE_COLOR4 = 0x4,
		VERTEX_TYPE_UBYTE4N = 0x5,
		VERTEX_TYPE_11_11_10N = 0x6,
		VERTEX_TYPE_HALF4 = 0x7,
		VERTEX_TYPE_HALF3 = 0x8,
		VERTEX_TYPE_SINT16_2 = 0x9,
		VERTEX_TYPE_SHORT4 = 0xA,
		VERTEX_TYPE_SHORT4N = 0xB,
		VERTEX_TYPE_SHORT4_FIXED4_12 = 0xC,
		VERTEX_TYPE_SHORT4_FIXED8_8 = 0xD,
		VERTEX_TYPE_UINT1 = 0xE,
		VERTEX_TYPE_UBYTE4_DELTA = 0xF,
		VERTEX_TYPE_BYTE4N = 0x10,
		NUM_VERTEX_TYPES = 0x11,
		VERTEX_TYPE_FORCE_DWORD = 0xFFFFFFFF,
	};

	enum eVertexStreamElementUsage
	{
		VERTEX_ELEMENT_POSITION = 0x0,
		VERTEX_ELEMENT_NORMAL = 0x1,
		VERTEX_ELEMENT_TANGENT = 0x2,
		VERTEX_ELEMENT_COLOR0 = 0x3,
		VERTEX_ELEMENT_COLOR1 = 0x4,
		VERTEX_ELEMENT_TEXCOORD0 = 0x5,
		VERTEX_ELEMENT_TEXCOORD1 = 0x6,
		VERTEX_ELEMENT_TEXCOORD2 = 0x7,
		VERTEX_ELEMENT_TEXCOORD3 = 0x8,
		VERTEX_ELEMENT_TEXCOORD4 = 0x9,
		VERTEX_ELEMENT_TEXCOORD5 = 0xA,
		VERTEX_ELEMENT_TEXCOORD6 = 0xB,
		VERTEX_ELEMENT_TEXCOORD7 = 0xC,
		VERTEX_ELEMENT_BLENDINDEX = 0xD,
		VERTEX_ELEMENT_BLENDWEIGHT = 0xE,
		VERTEX_ELEMENT_BINORMAL = 0xF,
		NUM_VERTEX_ELEMENTS = 0x10,
		VERTEX_ELEMENT_FORCE_DWORD = 0xFFFFFFFF,
	};
}